name: Cypress Tests

on: [push]

jobs:
  ESlint-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Run ESLint
        uses: actions/checkout@v2
        with:
           start: npm run lint


  Cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          start: npm run ci-test

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ./cypress/reports
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'